services:
  mysql:
    image: mysql:8.0
    container_name: dm-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dm_ecommerce
      MYSQL_USER: etl_user
      MYSQL_PASSWORD: etl_pass
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - ../mysql_data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost","-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer
    container_name: dm-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  webspoon:
    platform: linux/amd64
    image: hiromuhota/webspoon:latest
    container_name: dm-webspoon
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Xms512m -Xmx2g
    volumes:
      - ../etl:/data
      - ../staging:/staging:ro     # ← monta los CSV en /staging (solo lectura)
      - ../drivers/mysql-connector-j-9.0.0.jar:/usr/local/tomcat/webapps/spoon/WEB-INF/lib/mysql-connector-j.jar
      - ../drivers/mysql-connector-j-9.0.0.jar:/home/tomcat/.kettle/lib/mysql-connector-j.jar
    depends_on:
      mysql:
        condition: service_healthy


